// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD18406.Models;

#nullable disable

namespace SD18406.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20240711081521_hi")]
    partial class hi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD18406.Models.Catregory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c0b0dfaa-c070-4db6-aecb-95c8be9cd183"),
                            ImgURL = "Minh.png",
                            Name = "Jeans",
                            SoLuong = 145
                        },
                        new
                        {
                            ID = new Guid("dea6ee03-5b68-4ff2-9c52-957aa111da8f"),
                            ImgURL = "Minh.png",
                            Name = "Cots",
                            SoLuong = 12
                        },
                        new
                        {
                            ID = new Guid("4be8c48f-84f4-419e-a436-dafd2acbc3de"),
                            ImgURL = "Minh.png",
                            Name = "Blouse",
                            SoLuong = 145
                        },
                        new
                        {
                            ID = new Guid("488e8028-8105-46a4-a507-2e63d7f58cc5"),
                            ImgURL = "Minh.png",
                            Name = "Hat",
                            SoLuong = 16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
