// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice02.Models;

#nullable disable

namespace Practice02.Migrations
{
    [DbContext(typeof(WatchDbContext))]
    [Migration("20240712160554_hi")]
    partial class hi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Practice02.Models.Watch", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8d8c8d91-792b-42ad-8296-002d18b1da4b"),
                            Name = "Rolex 1912",
                            Origin = "US",
                            Price = 1788.0,
                            year = 1910
                        },
                        new
                        {
                            ID = new Guid("ac208ecd-2f22-416f-88a3-fee0f59d526f"),
                            Name = "Rolex 1989",
                            Origin = "UK",
                            Price = 5000.0,
                            year = 1970
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
