// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice02.Models;

#nullable disable

namespace Practice02.Migrations
{
    [DbContext(typeof(WatchDbContext))]
    partial class WatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Practice02.Models.Watch", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4a446c5d-98ff-482f-8b43-ef7b2c95bf3d"),
                            Img = "Minh.png",
                            Name = "Rolex 1912",
                            Origin = "US",
                            Price = 1788.0,
                            year = 1910
                        },
                        new
                        {
                            ID = new Guid("1fa40d85-dc55-41fd-bce4-c7e80a16c9fb"),
                            Img = "Minh.png",
                            Name = "Rolex 1989",
                            Origin = "UK",
                            Price = 5000.0,
                            year = 1970
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
