// <auto-generated />
using System;
using ASM1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM1.Migrations
{
    [DbContext(typeof(ASMDbContext))]
    partial class ASMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASM1.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("LopHocs");

                    b.HasData(
                        new
                        {
                            MaLop = "SD18401",
                            TenLop = "PTPM98"
                        });
                });

            modelBuilder.Entity("ASM1.Models.SinhVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ClassroomMaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClassroomMaLop");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            ID = new Guid("11811e1a-a9f7-4c9e-9fd0-ff4c7cb377be"),
                            Age = 20,
                            MaLop = "SD18401",
                            Major = "CNTT",
                            Name = "Nguyen Hong Minh"
                        });
                });

            modelBuilder.Entity("ASM1.Models.SinhVien", b =>
                {
                    b.HasOne("ASM1.Models.LopHoc", "Classroom")
                        .WithMany("SinhViens")
                        .HasForeignKey("ClassroomMaLop");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ASM1.Models.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
