// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice04.Models;

#nullable disable

namespace Practice04.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240717162642_minhd")]
    partial class minhd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Practice04.Models.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayxuatban")
                        .HasColumnType("datetime2");

                    b.Property<int>("soTrang")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("db48e214-3fbf-456c-b77c-6a682720456c"),
                            Title = "Nham mat cho mua ha",
                            ngayxuatban = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            soTrang = 187
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
