// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenHongMinh_BaoVeMon.Models;

#nullable disable

namespace NguyenHongMinh_BaoVeMon.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NguyenHongMinh_BaoVeMon.Models.CanHo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("So")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toaNhaID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("toaNhaID");

                    b.ToTable("Canhos");

                    b.HasData(
                        new
                        {
                            ID = "CH01",
                            DienTich = 290.0,
                            Name = "Nha1",
                            So = "20"
                        });
                });

            modelBuilder.Entity("NguyenHongMinh_BaoVeMon.Models.ToaNha", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("toanhas");
                });

            modelBuilder.Entity("NguyenHongMinh_BaoVeMon.Models.CanHo", b =>
                {
                    b.HasOne("NguyenHongMinh_BaoVeMon.Models.ToaNha", "toaNha")
                        .WithMany("CanHos")
                        .HasForeignKey("toaNhaID");

                    b.Navigation("toaNha");
                });

            modelBuilder.Entity("NguyenHongMinh_BaoVeMon.Models.ToaNha", b =>
                {
                    b.Navigation("CanHos");
                });
#pragma warning restore 612, 618
        }
    }
}
