// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice03.Models;

#nullable disable

namespace Practice03.Migrations
{
    [DbContext(typeof(RingDbContext))]
    [Migration("20240717125019_hiu")]
    partial class hiu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Practice03.Models.Ring", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rings");

                    b.HasData(
                        new
                        {
                            ID = new Guid("bc49c2dd-1281-403f-b024-f03a7bdcef09"),
                            Image = "Minh",
                            Name = "Ring Gold",
                            Origin = "VietNam"
                        },
                        new
                        {
                            ID = new Guid("12f29c76-5295-450c-980b-34312cdb6291"),
                            Image = "Minh",
                            Name = "Ring Clonium",
                            Origin = "VietNam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
