// <auto-generated />
using System;
using LuyenTap2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuyenTap2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LuyenTap2.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("LuyenTap2.Models.SinhVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuyenNghanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.Property<string>("khoahocMaKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("khoahocMaKhoaHoc");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0b7540f7-996e-4736-b0b9-37d4837a8fa0"),
                            ChuyenNghanh = "CNTT",
                            HoTen = "Nguyen Hong Minh",
                            Tuoi = 20
                        });
                });

            modelBuilder.Entity("LuyenTap2.Models.SinhVien", b =>
                {
                    b.HasOne("LuyenTap2.Models.KhoaHoc", "khoahoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("khoahocMaKhoaHoc");

                    b.Navigation("khoahoc");
                });

            modelBuilder.Entity("LuyenTap2.Models.KhoaHoc", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
